contentDir = "content"
layoutDir = "layouts"
publishDir = "docs"
buildDrafts = false
baseURL = "subcultureexplorer.lol"
canonifyURLs = true
title = "Subculture Explorer"
theme = "smigle"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  subtitle = "Subculture Explorer... lol"
  author = "Louis B"
